### ISSUE TITLE
Corner images fail to load under certain scenarios

### ISSUE THREAD

**Issue by jhammer** [TimOliver/TORoundedTableView#3]
We ran into an edge case in our use of `TORoundedTableView` (which is awesome, by the way):

If `-[TORoundedTableView layoutSubviews]` is called *before* the table view has been added to the view hierarchy, then the rounded corner images are not loaded in time, and the table view cells do not have a rounded corner appearance.

Why does this happen? Well, `-[TORoundedTableView layoutSubviews]` results in a call to `-[TORoundedTableViewCapCell didMoveToSuperview]`. When `TORoundedTableViewCapCell` tries to get the table view's `roundedCornerImage` in `-[TORoundedTableViewCapCell didMoveToSuperview]`, it won't be able to because the table view hasn't loaded them yet (which happens only once the table has been added to the view hierarchy in `-[TORoundedTableView  didMoveToSuperview]`).

My suggested fix is to eagerly call `loadCornerImages` inside of `-[TORoundedTableView  setUp]`, rather than lazily in `-[TORoundedTableView  didMoveToSuperview]`. This solved the problem for us.

The question you're probably asking is, why would `layoutSubviews` be called before the table is added to the view hierarchy? We ran into a situation where we have a table header view that is sized using auto layout and, in order for it to display correctly when the table first appears, we have to call `-[UITableView layoutIfNeeded]` inside our view controller's `viewDidLoad` method. This triggers all of the layout, even though the table view doesn't have a superview yet.

Thanks for considering this fix.

**Comment by TimOliver** [comment]
Hi @jhammer! Thanks so much for the report. I'm sorry it took so long for me to get to it.

Hmmm... that's an interesting scenario. Thanks for letting me know!

The reason I put it in `didMoveToSuperview` was to give the caller a chance to change the background color of the elements before they were generated.

I guess it's not a huge amount of overhead, but I'll also need to regenerate those images if the user changes any of those properties as well.

Thanks for the issue! I'm glad you liked the library! :)

**Comment by TimOliver** [comment]
Fixed! I'll push out a new release soon! (Hopefully!)
